### ISSUE TITLE
setup server creation command

### ISSUE THREAD

**Issue by TheTeaCup** [astronomybot/hosting-bot#1]
limit users to one server for now, then also keep count of how many servers they have.

**Comment by Jonfirexbox** [comment]
Did we add this yet?

**Comment by TheTeaCup** [comment]
> Did we add this yet?

it has not be added to the code, i need to finalize something's before i update the code. also could you open a new issue with the suggestions for our site thanks 😁

**Comment by Jonfirexbox** [comment]
> it has not be added to the code, i need to finalize something's before i update the code. also could you open a new issue with the suggestions for our site thanks 😁

Yes will do

**Comment by TheTeaCup** [comment]
> > it has not be added to the code, i need to finalize something's before i update the code. also could you open a new issue with the suggestions for our site thanks 😁
> 
> 
> 
> Yes will do

thanks you

**Comment by UnityLxthel** [comment]
I'm gonna rewrite the server creation server creating part of the bot to make it a bit easier to use.
